# Generated by Django 4.1.5 on 2023-02-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Coder', '0002_artista_cliente_proyectos_delete_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='imagen',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
